#!/usr/bin/python3
from sys import argv
from math import isqrt
if len(argv) != 2:
    print("error: Usage factors file_name")
    exit()
try:
    file = open(argv[1], "r")
    lines = file.readlines()
    for num in lines:
        n = int(num)
        if n % 2 == 0:
            q = 2
            p = n // q
            print("{:d}={:d}*{:d}".format(n, p, q))
            continue
        for q in range(3, isqrt(n) + 1, 2):
            if n % q == 0:
                break;
        p = n // q
        print("{:d}={:d}*{:d}".format(n, p, q))
except FileNotFoundError:
    print("file {:s} not found".format(argv[1]))
